<h1>Step 1: Get the datasets </h1>

In [36]:
import pandas as pd
import numpy as np


def load_weather_data(csv_file):
    city_attrib_csv_path = "datasets/" + csv_file
    return pd.read_csv(city_attrib_csv_path)

In [37]:
import tensorflow as tf

tf.test.is_built_with_cuda()
tf.test.is_gpu_available(cuda_only=False, min_cuda_compute_capability=None)

True

In [38]:
weather_data_with_labels = load_weather_data("weather_data_with_labels.csv")

In [39]:
weather_data_with_labels

month  day  hour_of_day   latitude   longitude  humidity  pressure  \
0           10    1           12  49.249660 -123.119339       NaN       NaN   
1           10    1           13  49.249660 -123.119339      76.0       NaN   
2           10    1           14  49.249660 -123.119339      76.0       NaN   
3           10    1           15  49.249660 -123.119339      76.0       NaN   
4           10    1           16  49.249660 -123.119339      77.0       NaN   
...        ...  ...          ...        ...         ...       ...       ...   
1629103     11   29           20  31.769039   35.216331       NaN       NaN   
1629104     11   29           21  31.769039   35.216331       NaN       NaN   
1629105     11   29           22  31.769039   35.216331       NaN       NaN   
1629106     11   29           23  31.769039   35.216331       NaN       NaN   
1629107     11   30            0  31.769039   35.216331       NaN       NaN   

         temperature weather_description  wind_direction  wind_speed  \
0                NaN                 NaN             NaN         NaN   
1         284.630000                mist             0.0         0.0   
2         284.629041       broken clouds             6.0         0.0   
3         284.626998       broken clouds            20.0         0.0   
4         284.624955       broken clouds            34.0         0.0   
...              ...                 ...             ...         ...   
1629103          NaN                 NaN             NaN         NaN   
1629104          NaN                 NaN             NaN         NaN   
1629105          NaN                 NaN             NaN         NaN   
1629106          NaN                 NaN             NaN         NaN   
1629107          NaN                 NaN             NaN         NaN   

         humidity_labels  pressure_labels  temperature_labels  \
0                   76.0              NaN          284.630000   
1                   76.0              NaN          284.629041   
2                   76.0              NaN          284.626998   
3                   77.0              NaN          284.624955   
4                   78.0              NaN          284.622911   
...                  ...              ...                 ...   
1629103              NaN              NaN                 NaN   
1629104              NaN              NaN                 NaN   
1629105              NaN              NaN                 NaN   
1629106              NaN              NaN                 NaN   
1629107              NaN              NaN                 NaN   

        description_labels  wind_direction_labels  wind_speed_labels  
0                     mist                    0.0                0.0  
1            broken clouds                    6.0                0.0  
2            broken clouds                   20.0                0.0  
3            broken clouds                   34.0                0.0  
4            broken clouds                   47.0                0.0  
...                    ...                    ...                ...  
1629103                NaN                    NaN                NaN  
1629104                NaN                    NaN                NaN  
1629105                NaN                    NaN                NaN  
1629106                NaN                    NaN                NaN  
1629107                NaN                    NaN                NaN  

[1629108 rows x 17 columns]

In [40]:
weather_data_with_labels = weather_data_with_labels.dropna(subset=["temperature"])
weather_data_with_labels = weather_data_with_labels.reset_index(drop=True)

In [41]:
weather_data_with_labels

month  day  hour_of_day   latitude   longitude  humidity  pressure  \
0           10    1           13  49.249660 -123.119339      76.0       NaN   
1           10    1           14  49.249660 -123.119339      76.0       NaN   
2           10    1           15  49.249660 -123.119339      76.0       NaN   
3           10    1           16  49.249660 -123.119339      77.0       NaN   
4           10    1           17  49.249660 -123.119339      78.0       NaN   
...        ...  ...          ...        ...         ...       ...       ...   
1621073     10   27           20  31.769039   35.216331      68.0    1011.0   
1621074     10   27           21  31.769039   35.216331      72.0    1011.0   
1621075     10   27           22  31.769039   35.216331      60.0    1011.0   
1621076     10   27           23  31.769039   35.216331      56.0    1011.0   
1621077     10   28            0  31.769039   35.216331      60.0    1011.0   

         temperature weather_description  wind_direction  wind_speed  \
0         284.630000                mist             0.0         0.0   
1         284.629041       broken clouds             6.0         0.0   
2         284.626998       broken clouds            20.0         0.0   
3         284.624955       broken clouds            34.0         0.0   
4         284.622911       broken clouds            47.0         0.0   
...              ...                 ...             ...         ...   
1621073   295.760000        sky is clear             0.0         1.0   
1621074   293.150000        sky is clear             0.0         1.0   
1621075   294.150000        sky is clear             0.0         1.0   
1621076   294.150000        sky is clear           150.0         3.0   
1621077   294.150000          few clouds             0.0         1.0   

         humidity_labels  pressure_labels  temperature_labels  \
0                   76.0              NaN          284.629041   
1                   76.0              NaN          284.626998   
2                   77.0              NaN          284.624955   
3                   78.0              NaN          284.622911   
4                   78.0              NaN          284.620868   
...                  ...              ...                 ...   
1621073             72.0           1011.0          293.150000   
1621074             60.0           1011.0          294.150000   
1621075             56.0           1011.0          294.150000   
1621076             60.0           1011.0          294.150000   
1621077              NaN              NaN                 NaN   

        description_labels  wind_direction_labels  wind_speed_labels  
0            broken clouds                    6.0                0.0  
1            broken clouds                   20.0                0.0  
2            broken clouds                   34.0                0.0  
3            broken clouds                   47.0                0.0  
4            broken clouds                   61.0                0.0  
...                    ...                    ...                ...  
1621073       sky is clear                    0.0                1.0  
1621074       sky is clear                    0.0                1.0  
1621075       sky is clear                  150.0                3.0  
1621076         few clouds                    0.0                1.0  
1621077                NaN                    NaN                NaN  

[1621078 rows x 17 columns]

In [42]:
training_set = weather_data_with_labels.iloc[:,7:8].values

In [43]:
training_set

array([[284.63      ],
       [284.62904131],
       [284.62699792],
       ...,
       [294.15      ],
       [294.15      ],
       [294.15      ]])

In [44]:
#Feature Scaling 
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range=(0,1))
training_set_scaled = sc.fit_transform(training_set)

In [45]:
from pickle import dump

# Save transformer
dump(sc, open('temperature_scaler.pkl', 'wb'))

In [46]:
from pickle import load

scaler = load(open('temperature_scaler.pkl', 'rb'))

In [47]:

def gethourlydata(past_hours=24):
    x_train = []
    y_train = []
    future_hours = 12

    # only using 50000 rows of the dataset for now
    # add previous hours to a row of the x_train dataset
    # add future hours for weather in y_train
    for i in range(0,50000):
        x_train.append(training_set_scaled[i : i + past_hours])     
        y_train.append(training_set_scaled[i + past_hours : i + future_hours + past_hours])

    x_train , y_train = np.array(x_train), np.array(y_train)
    #x_train = np.reshape(x_train, (x_train.shape[0] , x_train.shape[1], 1) )

    return np.array(x_train), np.array(y_train)

In [48]:
past_hours = 24
future_hours = 12
x_train, y_train = gethourlydata(past_hours=24)

In [49]:
x_train[35000:45000].shape[0]

10000

In [50]:
y_train[100:101]

array([[[0.53424889],
        [0.57101204],
        [0.60346503],
        [0.60726812],
        [0.61195859],
        [0.62514262],
        [0.62679062],
        [0.61614198],
        [0.60371857],
        [0.57088527],
        [0.5628988 ],
        [0.53386858]]])

In [51]:
x_valid, y_valid = x_train[35000:45000, :past_hours], y_train[35000:45000, :future_hours]
x_test, y_test = x_train[45000:, :past_hours], y_train[45000:, :future_hours]
x_train, y_train = x_train[:35000, :past_hours], y_train[:35000, :future_hours]

In [52]:
from tensorflow import keras

model = keras.models.Sequential([
    keras.layers.LSTM(30, return_sequences=True, input_shape=[None, 1]),
    keras.layers.LSTM(30, return_sequences=True),
    keras.layers.LSTM(30),
    keras.layers.Dense(12)
])

def last_time_step_mse(Y_true, Y_pred):
    return keras.metrics.mean_squared_error(Y_true[:, -1], Y_pred[:, -1])
#optimizer = keras.optimizers.Adam(lr=0.01)

model.compile(loss="mse", optimizer="adam")

In [53]:
y_valid[1]

array([[0.58799915],
       [0.56873019],
       [0.55389816],
       [0.53412212],
       [0.51979717],
       [0.510543  ],
       [0.50800761],
       [0.49418973],
       [0.49025988],
       [0.48582295],
       [0.47428692],
       [0.47213184]])

In [54]:
model.fit(x_train, y_train, epochs=200, validation_data=(x_valid, y_valid), 
         callbacks=[keras.callbacks.EarlyStopping(monitor='val_loss', patience=10)], batch_size=64)

Train on 35000 samples, validate on 10000 samples
Epoch 1/200
35000/35000 [==============================] - 8s 241us/sample - loss: 0.0079 - val_loss: 0.0014
Epoch 2/200
35000/35000 [==============================] - 5s 145us/sample - loss: 0.0012 - val_loss: 0.0014
Epoch 3/200
35000/35000 [==============================] - 5s 142us/sample - loss: 0.0011 - val_loss: 0.0013
Epoch 4/200
35000/35000 [==============================] - 5s 142us/sample - loss: 0.0010 - val_loss: 0.0011
Epoch 5/200
35000/35000 [==============================] - 5s 147us/sample - loss: 8.6095e-04 - val_loss: 0.0011
Epoch 6/200
35000/35000 [==============================] - 5s 142us/sample - loss: 7.9160e-04 - val_loss: 8.6968e-04
Epoch 7/200
35000/35000 [==============================] - 5s 141us/sample - loss: 7.3548e-04 - val_loss: 8.2227e-04
Epoch 8/200
35000/35000 [==============================] - 5s 150us/sample - loss: 7.2284e-04 - val_loss: 8.2064e-04
Epoch 9/200
35000/35000 [=========================

KeyboardInterrupt: 

In [20]:
testdataset = training_set_scaled[45000:45023]
realvalue = sc.inverse_transform(training_set_scaled[45023:45024])

In [55]:
# 23 hours - 7.8006e-04 loss
# 48 hours - 7.6 loss
# 12 hours - 5.16 loss
# 12 hours - 3.893 2 hidden layers one dense layer
# 24 hours - 3.1172 2 hidden LMST layers one dense layer
# 36 hours - 2.7172 2 hidden LMST layers one dense layer

# 12 hour forecast - 48 hours - loss 6.2021
#                    72 hours - loss 6.6
#                    48 hours - loss 5.9 with 2 hidden layers
#                    72 hours - loss 6.1 with 2 hidden layers and 48 neurons
mse_test = model.evaluate(x_test, y_test)

5000/5000 [==============================] - 1s 130us/sample - loss: 6.7141e-04


In [56]:
model.save_weights("temp_model_weights.h5")

In [512]:
model = keras.models.load_model("temp_model.h5")

In [148]:
mse_test = model.evaluate(x_test, y_test)

5000/5000 [==============================] - 1s 283us/sample - loss: 0.2459


In [27]:
x_test[2000:2001]

array([[[0.36513839],
        [0.36437777],
        [0.36513839],
        [0.36589901],
        [0.36596239],
        [0.36602578],
        [0.36818086],
        [0.37312487],
        [0.37806888],
        [0.38326643],
        [0.38630889],
        [0.38859075],
        [0.38846398],
        [0.38998521],
        [0.38681597],
        [0.38681597],
        [0.38973167],
        [0.39429537],
        [0.39353476],
        [0.39505599],
        [0.39505599],
        [0.39657722],
        [0.39695753],
        [0.39733784]]])

In [156]:
model.predict(x_test[2000:2001])

array([[0.35381725, 0.3596736 , 0.36333048, 0.367871  , 0.36936575,
        0.3753712 , 0.3830894 , 0.38936824, 0.400045  , 0.4061861 ,
        0.41096938, 0.41329512]], dtype=float32)

In [150]:
y_test[2000:2001]

array([[[0.34561589],
        [0.34561589],
        [0.40469047],
        [0.40469047],
        [0.40304247],
        [0.40228185],
        [0.40380308],
        [0.40392985],
        [0.40633847],
        [0.41140925],
        [0.41229664],
        [0.41381787]]])

In [170]:
keras.losses.mean_squared_error(y_test[110:115], y_pred)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.00067175, 0.00142141, 0.00113675, 0.00152775, 0.00079585],
      dtype=float32)>

In [83]:
from tensorflow import keras

In [84]:
regressor = keras.models.Sequential()

regressor.add(keras.layers.Bidirectional(keras.layers.LSTM(units=30, 
                                 return_sequences=True, 
                                 input_shape = (x_train.shape[1],1) ) ))
regressor.add(keras.layers.Dropout(0.2))

regressor.add(keras.layers.LSTM(units= 30 , return_sequences=True))
regressor.add(keras.layers.Dropout(0.2))

regressor.add(keras.layers.LSTM(units= 30 , return_sequences=True))
regressor.add(keras.layers.Dropout(0.2))

regressor.add(keras.layers.LSTM(units= 30))
regressor.add(keras.layers.Dropout(0.2))

regressor.add(keras.layers.Dense(units = n_future,activation='linear'))
regressor.compile(optimizer='adam', loss='mean_squared_error',metrics=['acc'])
regressor.fit(x_train, y_train, epochs=2,batch_size=128 )

Train on 50000 samples
Epoch 1/2
50000/50000 [==============================] - 47s 933us/sample - loss: 0.0130 - acc: 0.2425
Epoch 2/2
50000/50000 [==============================] - 40s 801us/sample - loss: 0.0044 - acc: 0.2451


In [86]:
testdataset = training_set_scaled[40000:40030]
print(sc.inverse_transform(testdataset))
realvalues = sc.inverse_transform(training_set_scaled[40030:40034])
print(realvalues)
testdataset = np.reshape(testdataset,(testdataset.shape[1],testdataset.shape[0],1))

[[283.33]
 [282.94]
 [282.55]
 [282.15]
 [282.54]
 [282.15]
 [282.54]
 [280.25]
 [280.95]
 [281.85]
 [283.42]
 [285.29]
 [286.3 ]
 [286.87]
 [286.86]
 [286.73]
 [286.88]
 [286.88]
 [286.02]
 [285.74]
 [284.33]
 [283.32]
 [282.37]
 [282.38]
 [281.99]
 [281.2 ]
 [280.6 ]
 [277.53]
 [276.99]
 [276.96]]
[[280.38]
 [281.02]
 [281.72]
 [282.32]]


In [88]:
predicted_temperature = regressor.predict(testdataset)
predicted_temperature = sc.inverse_transform(predicted_temperature)
predicted_temperature = np.reshape(predicted_temperature,(predicted_temperature.shape[1],predicted_temperature.shape[0]))

In [89]:
predicted_temperature

array([[282.9921 ],
       [283.04633],
       [283.08838],
       [283.04767]], dtype=float32)

In [90]:
realvalues

array([[280.38],
       [281.02],
       [281.72],
       [282.32]])

In [28]:
temperature_model = keras.models.load_model("temp_model.h5", custom_objects=None, compile=True)

In [29]:
dataset = [[[0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], ]]

In [32]:
dataset = np.array(dataset)

In [33]:
dataset.shape

(1, 24, 1)

In [34]:
temperature_model.predict(dataset)

array([[0.49810135, 0.5008137 , 0.501759  , 0.4999187 , 0.49991044,
        0.49921298, 0.49998742, 0.49981803, 0.5007866 , 0.4992501 ,
        0.4986806 , 0.4969843 ]], dtype=float32)

In [35]:
temperature_model = keras.models.load_model("temp_model.h5")

dataset = [[[0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5], [0.5]]]
dataset = np.array(dataset)

prediction = temperature_model.predict(dataset)

print(prediction)

[[0.49810135 0.5008137  0.501759   0.4999187  0.49991044 0.49921298
  0.49998742 0.49981803 0.5007866  0.4992501  0.4986806  0.4969843 ]]
